default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= ENV['FOODCLUBE_DATABASE_USER_DEVELOPMENT'] %>
  # password: <%= ENV['FOODCLUBE_DATABASE_PASSWORD_DEVELOPMENT'] %>
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: artist_development

test:
  <<: *default
  database: artist_test

production:
  <<: *default
  database: artist_production
  username: root
  password: password